name: build

on: [workflow_dispatch]

jobs:
  create-testing:
    if: github.ref == 'refs/heads/master' && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' )
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: |
          echo "MY_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ env.MY_DATE }}
          RELEASE_NAME: nightly-release-${{ env.MY_DATE }}

      # - name: Create latest build
      #   uses: czietz/action-automatic-releases@latest
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     automatic_release_tag: "20241022-111131"
      #     prerelease: false
      #     title: ${{ env.MY_DATE }}
      #     files: |
      #       *.zip
      #       *.7z

      - name: 'Build Changelog'
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.MY_DATE }}
          # generate_release_notes: true
          make_latest: true
          body: ${{steps.build_changelog.outputs.changelog}}
          
